import type { CollectionConfig, FieldAccess } from "payload";

/**
 * Better Auth `user` model, as a Payload-managed collection.
 *
 * This is the CUSTOMER user (distinct from the `admins` collection, which is
 * Payload's own superadmin login for `/admin`). Better Auth writes to this
 * collection through our custom BA -> Payload Local-API adapter
 * (`src/lib/better-auth-payload-adapter.ts`); Payload owns the schema.
 *
 * Field names mirror Better Auth's authoritative `user` schema exactly
 * (camelCase: `emailVerified`, `createdAt`, `updatedAt`) so the adapter can map
 * BA field -> Payload field 1:1 with no translation. See
 * `@better-auth/core` `getAuthTables()` for the source of truth.
 *
 * IDs: string UUIDs, generated by Postgres (`idType: 'uuid'` in
 * payload.config.ts). The adapter runs with `disableIdGeneration`, so BA never
 * sends an id and Payload/Postgres mints it.
 */

const adminOnlyAccess: FieldAccess = ({ req }) =>
  req.user?.collection === "admins";

export const Users: CollectionConfig = {
  slug: "users",
  admin: {
    useAsTitle: "email",
    group: "Auth (Better Auth)",
  },
  // NOTE: `auth: true` is intentionally NOT set. Payload-native auth would add
  // its own password/salt/hash columns and login machinery; Better Auth owns
  // credentials (hashed password lives on the `accounts` collection). This is a
  // plain data collection that BA drives.
  fields: [
    { name: "name", type: "text", required: true },
    { name: "email", type: "email", required: true, unique: true, index: true },
    {
      name: "emailVerified",
      type: "checkbox",
      required: true,
      defaultValue: false,
    },
    { name: "image", type: "text" },
    // createdAt / updatedAt are added automatically by Payload (timestamps),
    // matching BA's expected `createdAt` / `updatedAt` date fields.

    // role — self-elevation guard: only Payload admins (the `admins` collection) may set it.
    {
      name: "role",
      type: "select",
      required: true,
      defaultValue: "customer",
      options: ["customer", "gardener"],
      access: {
        create: adminOnlyAccess,
        update: adminOnlyAccess,
      },
    },
    // tenant — assigned on create by a later hook when unset.
    {
      name: "tenant",
      type: "relationship",
      relationTo: "tenants",
      required: true,
    },
  ],
  hooks: {
    beforeChange: [
      async ({ data, operation, req }) => {
        // Assign the single Kryscar tenant on create when unset. THIS hook is the
        // designated future home of customer→tenant routing logic — today a
        // one-liner (everyone → Kryscar), later the assignment system.
        if (operation === "create" && !data.tenant) {
          const res = await req.payload.find({
            collection: "tenants",
            where: { slug: { equals: "kryscar" } },
            limit: 1,
            depth: 0,
          });
          if (res.docs[0]) data.tenant = res.docs[0].id;
        }
        return data;
      },
    ],
  },
  timestamps: true,
};
