#!/usr/bin/env node
// Mind generator: verifies the Map against the code, writes map/index.md.
// DO NOT add app logic here — this is the-mind zone's implementation.
import { execSync } from "node:child_process";
import { readFileSync, writeFileSync, readdirSync, existsSync } from "node:fs";
import { join, relative } from "node:path";
import matter from "gray-matter";

const ROOT = process.cwd();
const VAULT = "kryscar-mind";
const ZONES_DIR = join(ROOT, VAULT, "map", "zones");
const FLOWS_DIR = join(ROOT, VAULT, "map", "flows");
const INDEX_PATH = join(ROOT, VAULT, "map", "index.md");

const sh = (cmd) => execSync(cmd, { cwd: ROOT, encoding: "utf8" }).trim();

// --- tracked files ---
const tracked = sh("git ls-files").split("\n").filter(Boolean);
const trackedSet = new Set(tracked);

// --- minimal glob: ** => any (incl /), * => any but / ---
function globToRegExp(glob) {
  let re = "";
  for (let i = 0; i < glob.length; i++) {
    const c = glob[i];
    if (c === "*") {
      if (glob[i + 1] === "*") { re += ".*"; i++; }
      else re += "[^/]*";
    } else if ("\\^$.|?+()[]{}".includes(c)) {
      re += "\\" + c;
    } else re += c;
  }
  return new RegExp("^" + re + "$");
}
const globMatches = (glob) =>
  trackedSet.has(glob) ? [glob] : tracked.filter((f) => globToRegExp(glob).test(f));

// --- exported symbol index ---
const SRC_EXT = /\.(ts|tsx|js|jsx|mjs|cjs)$/;
const exported = new Set();
const declRe =
  /export\s+(?:default\s+)?(?:async\s+)?(?:function|const|let|var|class|type|interface|enum)\s+([A-Za-z0-9_$]+)/g;
const listRe = /export\s*\{([^}]*)\}/g;
for (const f of tracked) {
  if (!SRC_EXT.test(f)) continue;
  let src;
  try { src = readFileSync(join(ROOT, f), "utf8"); } catch { continue; }
  let m;
  while ((m = declRe.exec(src))) exported.add(m[1]);
  while ((m = listRe.exec(src)))
    for (const part of m[1].split(","))
      exported.add(part.trim().split(/\s+as\s+/)[0].trim());
}

// --- route resolution ---
function routeResolves(route) {
  if (route === "/sitemap.xml") return trackedSet.has("src/app/sitemap.ts");
  if (route === "/robots.txt") return trackedSet.has("src/app/robots.ts");
  const p = route.replace(/^\//, "");
  const base = p === "" ? "src/app" : `src/app/${p}`;
  return trackedSet.has(`${base}/page.tsx`) || trackedSet.has(`${base}/page.ts`);
}

// --- anchor resolution ---
function anchorResolves(anchor) {
  const idx = anchor.indexOf(":");
  const kind = anchor.slice(0, idx);
  const val = anchor.slice(idx + 1);
  if (kind === "symbol") return exported.has(val);
  if (kind === "route") return routeResolves(val);
  if (kind === "glob") return globMatches(val).length > 0;
  return false;
}

// --- freshness ---
function isStale(zone) {
  const sha = (zone.verifiedAt || "").toString().trim();
  if (!sha) return true;
  let changed;
  try { changed = sh(`git diff --name-only ${sha} HEAD`).split("\n").filter(Boolean); }
  catch { return true; }
  const res = ((zone.owns && zone.owns.globs) || []).map(globToRegExp);
  return changed.some((f) => res.some((r) => r.test(f)));
}

// --- read notes ---
function readNotes(dir) {
  if (!existsSync(dir)) return [];
  return readdirSync(dir)
    .filter((f) => f.endsWith(".md"))
    .map((f) => {
      const { data } = matter(readFileSync(join(dir, f), "utf8"));
      return { slug: f.replace(/\.md$/, ""), ...data };
    });
}
const zones = readNotes(ZONES_DIR);
const flows = readNotes(FLOWS_DIR);

// --- verify ---
const hardErrors = [];
const gaps = [];
const rows = [];
const attic = [];

for (const z of zones) {
  if (z.status === "unmounted") { attic.push(z); continue; }
  const owns = z.owns || {};
  for (const g of owns.globs || [])
    if (globMatches(g).length === 0)
      hardErrors.push(`zone ${z.slug}: glob "${g}" matches no tracked file`);
  for (const a of owns.anchors || [])
    if (!anchorResolves(a))
      hardErrors.push(`zone ${z.slug}: anchor "${a}" does not resolve`);
  for (const r of owns.routes || [])
    if (!routeResolves(r))
      hardErrors.push(`zone ${z.slug}: route "${r}" does not resolve`);
  for (const inv of z.invariants || [])
    if (!inv.enforcedBy || inv.enforcedBy.length === 0)
      gaps.push(`zone ${z.slug}: invariant "${inv.rule}" has no enforcedBy`);
  rows.push({
    slug: z.slug,
    status: z.status || "active",
    fresh: isStale(z) ? "⚠ stale" : "✓ fresh",
    summary: (z.summary || "").replace(/\|/g, "\\|"),
  });
}

for (const fl of flows) {
  if (fl.status === "unmounted") continue;
  for (const step of fl.steps || [])
    if (!anchorResolves(step))
      hardErrors.push(`flow ${fl.slug}: step "${step}" does not resolve`);
}

// --- write index ---
rows.sort((a, b) => a.slug.localeCompare(b.slug));
let out = "";
out += "<!-- GENERATED by scripts/mind/generate.mjs — DO NOT HAND-EDIT. Run `npm run mind`. -->\n\n";
out += "# 🧠 kryscar-mind — Map index\n\n";
out += `_${rows.length} zones · ${gaps.length} verification gaps._\n\n`;
out += "| Zone | Status | Freshness | Summary |\n|---|---|---|---|\n";
for (const r of rows) out += `| [[${r.slug}]] | ${r.status} | ${r.fresh} | ${r.summary} |\n`;
out += "\n## ⚠ Verification gaps\n\n";
out += gaps.length ? gaps.map((g) => `- ${g}`).join("\n") + "\n" : "_None._\n";
out += "\n## Attic (unmounted)\n\n";
out += attic.length
  ? attic.map((z) => `- [[${z.slug}]] — ${z.summary || ""}`).join("\n") + "\n"
  : "_Empty._\n";
writeFileSync(INDEX_PATH, out);

// --- report ---
if (hardErrors.length) {
  console.error("✗ Mind: hard errors:\n" + hardErrors.map((e) => "  - " + e).join("\n"));
  process.exit(1);
}
console.log(`✓ Mind: ${rows.length} zones, ${gaps.length} gaps. Wrote ${relative(ROOT, INDEX_PATH)}.`);
