// scripts/gen-blur.mjs
// Generates src/lib/blur-data.ts — tiny base64 blur placeholders for the
// site's self-hosted images, consumed by <BlurImage> for next/image's
// placeholder="blur". Manual step (like fetch-stock.sh): run `npm run blur`
// after adding or replacing an image. Output is committed.
import { readdirSync, writeFileSync } from "node:fs";
import { join, relative, sep } from "node:path";
import sharp from "sharp";

// Resolved from file location (not cwd) so the script can be called from any directory.
const ROOT = join(import.meta.dirname, "..");
const PUBLIC_DIR = join(ROOT, "public");
const IMG_DIR = join(PUBLIC_DIR, "img");
const OUT = join(ROOT, "src", "lib", "blur-data.ts");
const EXT = /\.(jpe?g|png)$/i;

function walk(dir) {
  const files = [];
  for (const entry of readdirSync(dir, { withFileTypes: true })) {
    const full = join(dir, entry.name);
    if (entry.isDirectory()) files.push(...walk(full));
    else if (EXT.test(entry.name)) files.push(full);
  }
  return files;
}

async function main() {
  const files = walk(IMG_DIR).sort();
  const entries = {};
  for (const file of files) {
    // POSIX-style public path key, e.g. "/img/garden/lawnTexture.jpg"
    const key = "/" + relative(PUBLIC_DIR, file).split(sep).join("/");
    try {
      const buf = await sharp(file).resize(16).webp({ quality: 40 }).toBuffer();
      entries[key] = "data:image/webp;base64," + buf.toString("base64");
    } catch (err) {
      console.warn(`blur: skipped ${key}: ${err.message}`);
    }
  }

  const body = Object.keys(entries)
    .sort()
    .map((k) => `  ${JSON.stringify(k)}: ${JSON.stringify(entries[k])},`)
    .join("\n");

  const output = `// GENERATED by scripts/gen-blur.mjs — run \`npm run blur\`. DO NOT EDIT.
// Tiny 16px base64 WebP blur placeholders keyed by public image path,
// consumed by <BlurImage> for next/image placeholder="blur".
export const BLUR_DATA: Record<string, string> = {
${body}
};
`;

  writeFileSync(OUT, output);
  console.log(`blur: wrote ${Object.keys(entries).length} entries to ${relative(ROOT, OUT)}`);
}

main().catch((err) => {
  console.error(err);
  process.exit(1);
});
